name: "Enforce PR Conventions"
on: pull_request
jobs:
  enforce-conventions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
